global:
  scrape_interval: 15s  # How frequently to scrape targets by default.

scrape_configs:
  - job_name: 'service-one'
    static_configs:
      - targets: ['service-one:3000']  # Assumes service-one exposes metrics on port 3000.

  - job_name: 'service-two'
    static_configs:
      - targets: ['service-two:6000']  # Assumes service-two exposes metrics on port 6000.

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:16686']  # Assumes Jaeger exposes metrics on port 16686.

# Add any additional configurations below as needed.
